#Latihan 2
print("Latihan 2")
print("\tToko Mainan")
print("===============================")
nama= input("Masukkan Nama Pembeli: ")
kode_Mainan= input("Masukkan Kode Mainan: ")
harga= int(input("Masukkan Harga: Rp"))
jumlah_beli= int(input("Masukkan Jumlah Beli: "))
print("================================")
print("Nama Pembeli: " + (nama))
print("Kode Mainan: " + (kode_Mainan))
print("Harga: Rp." + str(harga))
print("Jumlah Beli: " + str(jumlah_beli))
print("Total Bayar: Rp." + str(harga * jumlah_beli))
print("================================")